# Site settings
title: Hustle Stress Repeat
email: will@dubsoft.net
description: > # this means to ignore newlines until "baseurl:"
  A Slack channel to discuss mental health, depression, and burnout in tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hustlestressrepeat.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
